swagger: '2.0'
info:
  version: '1'
  title: Course
  description: Maintains course information
  contact:
    name: Your name
host: 'localhost:8080'
basePath: /v1/course
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
    
    /:
        get:
            tags:
            - "Course"
            summary: "Gets all courses"
            description: ""
            operationId: "getCourses"
            consumes:
            - "application/json"
            produces:
            - "application/json"
            parameters: []
            responses:
                "200":
                    description: "A list of all cources"
                    schema:
                        $ref: "#/definitions/ArrayOfCourses"
                    x-exportParamName: "Body"
        post:
            tags:
                - "Course"
            description: ""
            summary: "Creates new course"
            operationId: "addCourse"
            consumes:
            - "application/json"
            produces:
            - "application/json"
            parameters:
                - in: "body"
                  name: "body"
                  description: "Representation of a course object to be created"
                  required: true
                  schema:
                      $ref: "#/definitions/Course"
            responses:
                "200":
                    description: "OK"
                    schema:
                        type: "integer"
                        format: "int64"
                        description: "Returns Id of created course"
    /{courseId}/addStudent:
        put:
            tags:
            - "Course"
            summary: "Add students to a specific course"
            description: "Adds students to the course. If the student is already added then it wont be added as a duplicate."
            operationId: "addStudentsToCourse"
            consumes:
            - "application/json"
            produces:
            - "application/json"
            parameters:
            - name: "courseId"
              in: "path"
              description: "courseId"
              required: true
              type: "integer"
              format: "int64"
              x-exportParamName: "CourseId"
            - in: "body"
              name: "body"
              description: "Identifiers of students to be added to the course"
              required: true
              schema:
                type: "object"
                properties:
                    studentId:
                        type: "integer"
                        format: "int64"
            x-exportParamName: "Body"
            responses:
                "200":
                    description: "The student is added to the course"
    /{courseId}/student/{studentId}:
        delete:
            tags:
            - "Course"
            summary: "Removes student from the course"
            description: ""
            operationId: "removeStudentFromCourse"
            consumes:
            - "application/json"
            produces:
            - "application/json"
            parameters:
              - name: "courseId"
                in: "path"
                required: true
                type: "integer"
                format: "int64"
                x-exportParamName: "CourseId"
              - name: "studentId"
                in: "path"
                required: true
                type: "integer"
                format: "int64"
            x-exportParamName: "StudentId"
            responses:
                "200":
                    description: "Course deleted"
    /{courseId}:
      delete:
        tags:
        - "Course"
        summary: "Deletes a course"
        description: ""
        operationId: "deleteCourse"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
          - name: "courseId"
            in: "path"
            required: true
            type: "integer"
            format: "int64"
            x-exportParamName: "CourseId"
        responses:
          "200":
            description: "Course deleted"
definitions:
    Course:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        description:
          type: "string"
        teacher:
          type: "integer"
          format: "int64"
        students:
          type: "array"
          items:
            type: "integer"
            format: "int64"
    ArrayOfCourses:
      type: "array"
      items:
        $ref: "#/definitions/Course"